[project]
name = "pathfinding-playground"
version = "0.1.0"
description = "A Python implementation of the A* pathfinding algorithm, built from scratch"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "perlin-noise",
]


[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.uv.sources]
perlin-noise = { git = "https://github.com/BennPo/perlin-noise.git" }
